//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerSimulator.StationSimulatorReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StationSimulatorReference.IStationSimulatorService")]
    public interface IStationSimulatorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationSimulatorService/RegisterPackageFromClient", ReplyAction="http://tempuri.org/IStationSimulatorService/RegisterPackageFromClientResponse")]
        bool RegisterPackageFromClient(DronePost.SupportClasses.GeneratedPackage package);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationSimulatorService/RegisterPackageFromClient", ReplyAction="http://tempuri.org/IStationSimulatorService/RegisterPackageFromClientResponse")]
        System.Threading.Tasks.Task<bool> RegisterPackageFromClientAsync(DronePost.SupportClasses.GeneratedPackage package);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationSimulatorService/CommitArrival", ReplyAction="http://tempuri.org/IStationSimulatorService/CommitArrivalResponse")]
        void CommitArrival(DronePost.DataModel.Drone drone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationSimulatorService/CommitArrival", ReplyAction="http://tempuri.org/IStationSimulatorService/CommitArrivalResponse")]
        System.Threading.Tasks.Task CommitArrivalAsync(DronePost.DataModel.Drone drone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationSimulatorService/RequestCharge", ReplyAction="http://tempuri.org/IStationSimulatorService/RequestChargeResponse")]
        DronePost.SupportClasses.ChargeRespond RequestCharge();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStationSimulatorService/RequestCharge", ReplyAction="http://tempuri.org/IStationSimulatorService/RequestChargeResponse")]
        System.Threading.Tasks.Task<DronePost.SupportClasses.ChargeRespond> RequestChargeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStationSimulatorServiceChannel : CustomerSimulator.StationSimulatorReference.IStationSimulatorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StationSimulatorServiceClient : System.ServiceModel.ClientBase<CustomerSimulator.StationSimulatorReference.IStationSimulatorService>, CustomerSimulator.StationSimulatorReference.IStationSimulatorService {
        
        public StationSimulatorServiceClient() {
        }
        
        public StationSimulatorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StationSimulatorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StationSimulatorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StationSimulatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegisterPackageFromClient(DronePost.SupportClasses.GeneratedPackage package) {
            return base.Channel.RegisterPackageFromClient(package);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterPackageFromClientAsync(DronePost.SupportClasses.GeneratedPackage package) {
            return base.Channel.RegisterPackageFromClientAsync(package);
        }
        
        public void CommitArrival(DronePost.DataModel.Drone drone) {
            base.Channel.CommitArrival(drone);
        }
        
        public System.Threading.Tasks.Task CommitArrivalAsync(DronePost.DataModel.Drone drone) {
            return base.Channel.CommitArrivalAsync(drone);
        }
        
        public DronePost.SupportClasses.ChargeRespond RequestCharge() {
            return base.Channel.RequestCharge();
        }
        
        public System.Threading.Tasks.Task<DronePost.SupportClasses.ChargeRespond> RequestChargeAsync() {
            return base.Channel.RequestChargeAsync();
        }
    }
}
